-- =====================================================
-- Cleanup Script - Drop All Objects
-- Use with caution - this will delete all data!
-- =====================================================

-- Drop Packages
BEGIN
   EXECUTE IMMEDIATE 'DROP PACKAGE PKG_KPI_CALCULATIONS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP PACKAGE PKG_DATA_VALIDATION';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP PACKAGE PKG_ERROR_LOGGING';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

-- Drop Sequences
DROP SEQUENCE SEQ_ERROR_ID;
DROP SEQUENCE SEQ_VALIDATION_ID;
DROP SEQUENCE SEQ_KPI_ID;
DROP SEQUENCE SEQ_TRANSACTION_ID;
DROP SEQUENCE SEQ_PRODUCT_ID;
DROP SEQUENCE SEQ_CUSTOMER_ID;
DROP SEQUENCE SEQ_REGION_ID;

-- Drop Tables
DROP TABLE ERROR_LOG CASCADE CONSTRAINTS;
DROP TABLE DATA_VALIDATION_LOG CASCADE CONSTRAINTS;
DROP TABLE KPI_RESULTS CASCADE CONSTRAINTS;
DROP TABLE SALES_TRANSACTIONS CASCADE CONSTRAINTS;
DROP TABLE PRODUCTS CASCADE CONSTRAINTS;
DROP TABLE CUSTOMERS CASCADE CONSTRAINTS;
DROP TABLE REGIONS CASCADE CONSTRAINTS;

PROMPT =====================================================
PROMPT All objects dropped successfully!
PROMPT =====================================================

COMMIT;

