-- =====================================================
-- Enterprise Sales Analytics Database Schema
-- =====================================================

-- Drop tables if they exist (for clean setup)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SALES_TRANSACTIONS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CUSTOMERS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE PRODUCTS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE REGIONS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE KPI_RESULTS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DATA_VALIDATION_LOG CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ERROR_LOG CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

-- =====================================================
-- Reference Tables
-- =====================================================

-- Regions Table
CREATE TABLE REGIONS (
    REGION_ID NUMBER(10) PRIMARY KEY,
    REGION_NAME VARCHAR2(100) NOT NULL,
    REGION_CODE VARCHAR2(10) NOT NULL UNIQUE,
    COUNTRY VARCHAR2(100),
    CREATED_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT CHK_REGION_ID CHECK (REGION_ID > 0)
);

-- Customers Table
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER(10) PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(200) NOT NULL,
    CUSTOMER_CODE VARCHAR2(50) NOT NULL UNIQUE,
    REGION_ID NUMBER(10),
    CUSTOMER_TYPE VARCHAR2(50),
    CREATED_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_CUSTOMER_REGION FOREIGN KEY (REGION_ID) REFERENCES REGIONS(REGION_ID),
    CONSTRAINT CHK_CUSTOMER_ID CHECK (CUSTOMER_ID > 0)
);

-- Products Table
CREATE TABLE PRODUCTS (
    PRODUCT_ID NUMBER(10) PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(200) NOT NULL,
    PRODUCT_CODE VARCHAR2(50) NOT NULL UNIQUE,
    CATEGORY VARCHAR2(100),
    UNIT_PRICE NUMBER(10,2),
    CREATED_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT CHK_PRODUCT_ID CHECK (PRODUCT_ID > 0),
    CONSTRAINT CHK_UNIT_PRICE CHECK (UNIT_PRICE >= 0)
);

-- =====================================================
-- Transaction Table
-- =====================================================

-- Sales Transactions Table
CREATE TABLE SALES_TRANSACTIONS (
    TRANSACTION_ID NUMBER(10) PRIMARY KEY,
    TRANSACTION_DATE DATE NOT NULL,
    CUSTOMER_ID NUMBER(10) NOT NULL,
    PRODUCT_ID NUMBER(10) NOT NULL,
    QUANTITY NUMBER(10,2) NOT NULL,
    UNIT_PRICE NUMBER(10,2) NOT NULL,
    TOTAL_AMOUNT NUMBER(12,2) NOT NULL,
    REGION_ID NUMBER(10),
    DISCOUNT_PERCENTAGE NUMBER(5,2) DEFAULT 0,
    LOAD_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_SALES_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    CONSTRAINT FK_SALES_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    CONSTRAINT FK_SALES_REGION FOREIGN KEY (REGION_ID) REFERENCES REGIONS(REGION_ID),
    CONSTRAINT CHK_TRANSACTION_ID CHECK (TRANSACTION_ID > 0),
    CONSTRAINT CHK_QUANTITY CHECK (QUANTITY > 0),
    CONSTRAINT CHK_UNIT_PRICE_POS CHECK (UNIT_PRICE > 0),
    CONSTRAINT CHK_TOTAL_AMOUNT CHECK (TOTAL_AMOUNT >= 0),
    CONSTRAINT CHK_DISCOUNT CHECK (DISCOUNT_PERCENTAGE >= 0 AND DISCOUNT_PERCENTAGE <= 100)
);

-- =====================================================
-- Analytics & Logging Tables
-- =====================================================

-- KPI Results Table
CREATE TABLE KPI_RESULTS (
    KPI_ID NUMBER(10) PRIMARY KEY,
    KPI_NAME VARCHAR2(100) NOT NULL,
    KPI_VALUE NUMBER(15,2),
    KPI_DATE DATE NOT NULL,
    REGION_ID NUMBER(10),
    CALCULATION_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_KPI_REGION FOREIGN KEY (REGION_ID) REFERENCES REGIONS(REGION_ID)
);

-- Data Validation Log Table
CREATE TABLE DATA_VALIDATION_LOG (
    VALIDATION_ID NUMBER(10) PRIMARY KEY,
    VALIDATION_DATE DATE DEFAULT SYSDATE,
    TABLE_NAME VARCHAR2(100),
    VALIDATION_TYPE VARCHAR2(50),
    RECORDS_CHECKED NUMBER(10),
    RECORDS_PASSED NUMBER(10),
    RECORDS_FAILED NUMBER(10),
    VALIDATION_STATUS VARCHAR2(20),
    ERROR_DETAILS CLOB,
    CONSTRAINT CHK_VAL_STATUS CHECK (VALIDATION_STATUS IN ('PASS', 'FAIL', 'WARNING'))
);

-- Error Log Table
CREATE TABLE ERROR_LOG (
    ERROR_ID NUMBER(10) PRIMARY KEY,
    ERROR_DATE DATE DEFAULT SYSDATE,
    ERROR_SOURCE VARCHAR2(100),
    ERROR_TYPE VARCHAR2(50),
    ERROR_MESSAGE VARCHAR2(4000),
    ERROR_STACK CLOB,
    RESOLUTION_STATUS VARCHAR2(20) DEFAULT 'PENDING',
    CONSTRAINT CHK_RESOLUTION_STATUS CHECK (RESOLUTION_STATUS IN ('PENDING', 'RESOLVED', 'IGNORED'))
);

-- =====================================================
-- Comments for Documentation
-- =====================================================

COMMENT ON TABLE SALES_TRANSACTIONS IS 'Main fact table storing all sales transaction data';
COMMENT ON TABLE CUSTOMERS IS 'Customer master data';
COMMENT ON TABLE PRODUCTS IS 'Product master data';
COMMENT ON TABLE REGIONS IS 'Geographic region master data';
COMMENT ON TABLE KPI_RESULTS IS 'Stores calculated KPI values for reporting';
COMMENT ON TABLE DATA_VALIDATION_LOG IS 'Logs all data validation activities';
COMMENT ON TABLE ERROR_LOG IS 'Centralized error logging table';

COMMIT;

