-- =====================================================
-- Performance Indexes for Sales Analytics
-- =====================================================

-- Indexes on SALES_TRANSACTIONS (most queried table)
CREATE INDEX IDX_SALES_TRANS_DATE ON SALES_TRANSACTIONS(TRANSACTION_DATE);
CREATE INDEX IDX_SALES_CUSTOMER ON SALES_TRANSACTIONS(CUSTOMER_ID);
CREATE INDEX IDX_SALES_PRODUCT ON SALES_TRANSACTIONS(PRODUCT_ID);
CREATE INDEX IDX_SALES_REGION ON SALES_TRANSACTIONS(REGION_ID);
CREATE INDEX IDX_SALES_DATE_REGION ON SALES_TRANSACTIONS(TRANSACTION_DATE, REGION_ID);
CREATE INDEX IDX_SALES_DATE_CUSTOMER ON SALES_TRANSACTIONS(TRANSACTION_DATE, CUSTOMER_ID);

-- Indexes on KPI_RESULTS
CREATE INDEX IDX_KPI_NAME_DATE ON KPI_RESULTS(KPI_NAME, KPI_DATE);
CREATE INDEX IDX_KPI_REGION ON KPI_RESULTS(REGION_ID);
CREATE INDEX IDX_KPI_DATE ON KPI_RESULTS(KPI_DATE);

-- Indexes on Validation and Error Logs
CREATE INDEX IDX_VALIDATION_DATE ON DATA_VALIDATION_LOG(VALIDATION_DATE);
CREATE INDEX IDX_VALIDATION_STATUS ON DATA_VALIDATION_LOG(VALIDATION_STATUS);
CREATE INDEX IDX_ERROR_DATE ON ERROR_LOG(ERROR_DATE);
CREATE INDEX IDX_ERROR_STATUS ON ERROR_LOG(RESOLUTION_STATUS);

-- Indexes on Reference Tables
CREATE INDEX IDX_CUSTOMER_REGION ON CUSTOMERS(REGION_ID);
CREATE INDEX IDX_CUSTOMER_CODE ON CUSTOMERS(CUSTOMER_CODE);

COMMIT;

