-- =====================================================
-- Sequences for Primary Keys
-- =====================================================

CREATE SEQUENCE SEQ_REGION_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CUSTOMER_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PRODUCT_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TRANSACTION_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_KPI_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_VALIDATION_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ERROR_ID START WITH 1 INCREMENT BY 1;

COMMIT;

